/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ConversionReport {
  converter: string
  version: string
  source: string
  sourceFormat: string
  outputDirectory: string
  elapsedMs: number
  inputBytes: number
  pageCount: number
  largestPageIrBytes: number
  pages: Array<PageReport>
  warnings: Array<string>
}

export declare function convert(inputPath: string, outputDirectory: string, options?: ConvertOptions | undefined | null): Promise<ConversionReport>

export interface ConvertOptions {
  maxInputBytes?: number
  maxZipEntryBytes?: number
  maxPages?: number
  maxXmlEvents?: number
  includeMetadata?: boolean
  precision?: number
  jobs?: number
  outlineEmbeddedPdfText?: boolean
}

export interface PageReport {
  number: number
  svg: string
  widthPoints: number
  heightPoints: number
  nodeCount: number
  warningCount: number
  warnings: Array<string>
  estimatedIrBytes: number
}

/**
 * Convert a PDF/PPTX/XLSX/DOCX file and return complete SVG markup for UI
 * preview without leaving output files behind.
 *
 * This runs on a libuv worker. It is intended for Node.js, Electron main
 * processes, and server-side TypeScript; it is not a browser-WASM API.
 */
export declare function preview(inputPath: string, options?: PreviewOptions | undefined | null): Promise<PreviewReport>

/**
 * Options for an in-memory SVG preview.
 *
 * Conversion limits match `ConvertOptions`. The two preview limits bound how
 * much generated SVG is retained in the Node.js process at once.
 */
export interface PreviewOptions {
  maxInputBytes?: number
  maxZipEntryBytes?: number
  maxPages?: number
  maxXmlEvents?: number
  includeMetadata?: boolean
  precision?: number
  jobs?: number
  outlineEmbeddedPdfText?: boolean
  /** Maximum UTF-8 byte length of one returned SVG. Default: 64 MiB. */
  maxSvgBytes?: number
  /** Maximum UTF-8 byte length of all returned SVG pages. Default: 256 MiB. */
  maxTotalSvgBytes?: number
}

export interface PreviewPage {
  number: number
  /** Complete UTF-8 SVG markup, ready to put in a Blob for display. */
  svg: string
  widthPoints: number
  heightPoints: number
  nodeCount: number
  warningCount: number
  warnings: Array<string>
  estimatedIrBytes: number
}

export interface PreviewReport {
  converter: string
  version: string
  source: string
  sourceFormat: string
  elapsedMs: number
  inputBytes: number
  pageCount: number
  largestPageIrBytes: number
  pages: Array<PreviewPage>
  warnings: Array<string>
  /** True when the document or any page has a conversion warning. */
  needsReview: boolean
}

/**
 * Package one SVG or a directory of SVG pages as PPTX, DOCX, or XLSX.
 *
 * SVG pages remain vector images; Office semantic structure is not reconstructed.
 */
export declare function reverse(inputPath: string, outputPath: string, options?: ReverseOptions | undefined | null): Promise<ReverseReport>

export interface ReverseOptions {
  maxInputBytes?: number
  maxPages?: number
}

export interface ReverseReport {
  converter: string
  version: string
  source: string
  output: string
  outputFormat: string
  pageCount: number
  inputBytes: number
  warnings: Array<string>
}
