/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export interface ConversionReport {
  converter: string
  version: string
  source: string
  sourceFormat: string
  outputDirectory: string
  elapsedMs: number
  inputBytes: number
  pageCount: number
  largestPageIrBytes: number
  pages: Array<PageReport>
  warnings: Array<string>
}

export declare function convert(inputPath: string, outputDirectory: string, options?: ConvertOptions | undefined | null): Promise<ConversionReport>

export interface ConvertOptions {
  maxInputBytes?: number
  maxZipEntryBytes?: number
  maxPages?: number
  maxXmlEvents?: number
  includeMetadata?: boolean
  precision?: number
  jobs?: number
  outlineEmbeddedPdfText?: boolean
  embedDrawioSource?: boolean
  stencilPaths?: Array<string>
}

export interface PageReport {
  number: number
  svg: string
  widthPoints: number
  heightPoints: number
  nodeCount: number
  warningCount: number
  warnings: Array<string>
  estimatedIrBytes: number
}

/**
 * Convert a PDF/PPTX/XLSX/DOCX/drawio file and return complete SVG markup for UI
 * preview without leaving output files behind.
 *
 * This runs on a libuv worker. It is intended for Node.js, Electron main
 * processes, and server-side TypeScript; it is not a browser-WASM API.
 */
export declare function preview(inputPath: string, options?: PreviewOptions | undefined | null): Promise<PreviewReport>

/**
 * Options for an in-memory SVG preview.
 *
 * Conversion limits match `ConvertOptions`. The two preview limits bound how
 * much generated SVG is retained in the Node.js process at once.
 */
export interface PreviewOptions {
  maxInputBytes?: number
  maxZipEntryBytes?: number
  maxPages?: number
  maxXmlEvents?: number
  includeMetadata?: boolean
  precision?: number
  jobs?: number
  outlineEmbeddedPdfText?: boolean
  embedDrawioSource?: boolean
  stencilPaths?: Array<string>
  /** Maximum UTF-8 byte length of one returned SVG. Default: 64 MiB. */
  maxSvgBytes?: number
  /** Maximum UTF-8 byte length of all returned SVG pages. Default: 256 MiB. */
  maxTotalSvgBytes?: number
}

export interface PreviewPage {
  number: number
  /** Complete UTF-8 SVG markup, ready to put in a Blob for display. */
  svg: string
  widthPoints: number
  heightPoints: number
  nodeCount: number
  warningCount: number
  warnings: Array<string>
  estimatedIrBytes: number
}

export interface PreviewReport {
  converter: string
  version: string
  source: string
  sourceFormat: string
  elapsedMs: number
  inputBytes: number
  pageCount: number
  largestPageIrBytes: number
  pages: Array<PreviewPage>
  warnings: Array<string>
  /** True when the document or any page has a conversion warning. */
  needsReview: boolean
}

/**
 * Package one SVG or a directory of SVG pages as PPTX, DOCX, XLSX, draw.io, or CAD (DXF, G-code, Gerber, HP-GL).
 *
 * SVG pages remain vector images/geometry; Office semantic structure is not reconstructed.
 */
export declare function reverse(inputPath: string, outputPath: string, options?: ReverseOptions | undefined | null): Promise<ReverseReport>

export interface ReverseOptions {
  maxInputBytes?: number
  maxPages?: number
}

export interface ReverseReport {
  converter: string
  version: string
  source: string
  output: string
  outputFormat: string
  pageCount: number
  inputBytes: number
  warnings: Array<string>
}

/** Transform and optimize an SVG string (minify, monochrome, responsive scaling, precision rounding, and metadata stripping). */
export declare function transform(svg: string, options?: TransformOptions | undefined | null): string

export interface TransformOptions {
  minify?: boolean
  monochrome?: string
  responsive?: boolean
  precision?: number
  removeMetadata?: boolean
  cleanPaths?: boolean
  stripEmptyGroups?: boolean
}
